version: '3.8'
services:
  db1:
    image: mariadb:10.2
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mimic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db1_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  db2:
    image: mariadb:10.3
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mimic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db2_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  db3:
    image: mysql:5.7
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mimic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db3_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  s1:
    container_name: s1
    build:
      context: ./server/server1
    environment:
      - SERVER_NAME=Server 1
      - DB_HOST=db1
      - DB_NAME=mimic_db
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - 8001:80
    volumes:
      - ./server/src:/var/www/html
    depends_on:
      - db1

  s2:
    container_name: s2
    build:
      context: ./server/server2
    environment:
      - SERVER_NAME=Server 2
      - DB_HOST=db2
      - DB_NAME=mimic_db
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - 8002:80
    volumes:
      - ./server/src:/var/www/html
    depends_on:
      - db2

  s3:
    container_name: s3
    build:
      context: ./server/server3
    environment:
      - SERVER_NAME=Server 3
      - DB_HOST=db3
      - DB_NAME=mimic_db
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - 8003:80
    volumes:
      - ./server/src:/var/www/html
    depends_on:
      - db3

  waf:
    container_name: waf
    build:
      context: ./waf
    ports:
      - 8080:80
      - 9090:9090

  arbitrator:
    container_name: arbitrator
    build:
      context: ./arbitrator
    ports:
      - 8880:80
    depends_on:
      - waf
      - s1
      - s2
      - s3

volumes:
  db1_data:
  db2_data:
  db3_data:
