version: '3.7'

services:
  arbitrator:
    build: ./arbitrator
    container_name: arbitrator
    ports:
      - "80:80"
    depends_on:
      - s1
      - s2
      - s3
      - waf

  waf:
    build: ./waf
    container_name: waf
    ports:
      - "8080:80"
      - "9090:9090"

  s1:
    build:
      context: .
      dockerfile: server/server1/Dockerfile
    container_name: s1
    environment:
      - HTTP_SERVER=apache
      - PHP_VERSION=7.0.5
      - DB_VERSION=10.2.14
    ports:
      - "8081:80"

  s2:
    build:
      context: .
      dockerfile: server/server2/Dockerfile
    container_name: s2
    environment:
      - HTTP_SERVER=caddy
      - PHP_VERSION=7.3.13
      - DB_VERSION=10.3.27
    ports:
      - "8082:80"

  s3:
    build:
      context: .
      dockerfile: server/server3/Dockerfile
    container_name: s3
    environment:
      - HTTP_SERVER=nginx
      - PHP_VERSION=7.2.5
      - DB_VERSION=5.7.33
    ports:
      - "8083:80"
